<script type="text/javascript" src="./assets/js/jquery.min.js"></script>
<script type="text/javascript" src="./assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="./assets/js/jquery.easing.js"></script>
<script type="text/javascript" src="./assets/js/jquery-validate.js"></script>
<script type="text/javascript" src="./assets/js/jquery.isotope.min.js"></script>
<script type="text/javascript" src="./assets/js/imagesloaded.min.js"></script>
<script type="text/javascript" src="./assets/js/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="./assets/js/jquery-waypoints.js"></script>
<script type="text/javascript" src="./assets/js/parallax.js"></script>
<script type="text/javascript" src="./assets/js/smoothscroll.js"></script>
<script type="text/javascript" src="./assets/js/jquery-countTo.js"></script>
<script type="text/javascript" src="./assets/js/owl.carousel.js"></script>
<script type="text/javascript" src="./assets/js/jquery.easypiechart.min.js"></script>
<script type="text/javascript" src="./assets/js/jquery.bxslider.js"></script>
<script type="text/javascript" src="./assets/js/jquery.cookie.js"></script>
<script type="text/javascript" src="./assets/js/jquery.fitvids.js"></script>
<script type="text/javascript" src="./assets/js/jquery.tweet.min.js"></script>
<script type="text/javascript" src="./assets/js/jquery.fancybox.js"></script>
<script type="text/javascript" src="./assets/js/main.js"></script>
<script type="text/javascript" src="./assets/js/jquery.magnific-popup.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHtWltCIolOgzpMEfi_GVZZHCkrXH10SM&region=TR"></script>
<script type="text/javascript" src="./assets/js/gmap3.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/slider.js"></script>
<script type="text/javascript" src="./assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script type="text/javascript" src="./assets/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script src='https://www.google.com/recaptcha/api.js'></script>